# Generated by Django 3.0.5 on 2022-04-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Comment',
            old_name= 'comment',
            new_name= 'body'

        ),
    ]
